workflows:
  android-workflow:
    name: Android Build APK
    max_build_duration: 30
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
    scripts:
      - name: Force Upgrade Gradle and Build
        script: |
          cd app
          
          # ඇප් එකට අවශ්‍ය කරන Gradle 9.3.1 සංස්කරණය සර්වර් එකට ඩවුන්ලෝඩ් කරනවා
          echo "Downloading Gradle 9.3.1..."
          wget https://services.gradle.org/distributions/gradle-9.3.1-bin.zip -P /tmp
          sudo unzip -d /opt/gradle /tmp/gradle-9.3.1-bin.zip
          export PATH=/opt/gradle/gradle-9.3.1/bin:$PATH
          
          # නිවැරදි වර්ෂන් එක සෙට් වුණාදැයි පරික්ෂා කිරීම
          gradle -v
          
          # Android SDK එක සම්බන්ධ කිරීම
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          
          # අලුත් වර්ෂන් එකෙන් බිල්ඩ් එක ස්ටාර්ට් කිරීම
          gradle assembleDebug
    artifacts:
      - "**/build/outputs/apk/debug/*.apk"
